let nab=[
    {
        name:"Home",
        path:"/",
        subNav:[]
    },
    {
        name:"Movie",
        path:"/movie",
        subNav:[]
    },
    {
        name:"About",
        path:"/about",
        subNav:[]
    },
    {
        name:"Reducer",
        path:"/reducer",
        subNav:[]
    },
    {
        name:"Fruits",
        path:"/fruits",
        subNav:[]
    },
    {
        name:"ClassComponent",
        path:"/classcomponent",
        subNav:[]
    },
    {
        name:"Memo",
        path:"/memo",
        subNav:[]
    },
    {
        name:"Product",
        path:"/product",
        subNav:[
            {
                name:"Bike",
                path:"/product/bike",
                subNav:[]
            },
            {
                name:"Car",
                path:"/product/car",
                subNav:[]
            },
            {
                name:"Scooter",
                path:"/product/scooter",
                subNav:[]
            },
            

        ]
    },
    {
        name:"Contact",
        path:"/contact",
        subNav:[]
    },
]
export default nab;